apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  labels:
    app: devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
      - name: devops-app
        image: europe-west4-docker.pkg.dev/devops-project-448307/devops-repo/devops-app:PLACEHOLDER_TAG
        ports:
        - containerPort: 8000
        env:
          - name: PORT
            value: "8000"