name: Push to Artifact Registry

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'

env:
  WORKING_DIR: app/
  IMAGE_NAME: 'devops-app'
  PROJECT_ID: 'devops-project-448307'
  AR_REPO_LOCATION: 'europe-west4'
  AR_URL: 'europe-west4-docker.pkg.dev/devops-project-448307/devops-repo'

jobs:
  build_and_push:
    permissions:
      contents: read
      id-token: write
      security-events: write

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: 'true'
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}
          service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker for gcloud
        run: |-
          gcloud auth configure-docker ${{ env.AR_REPO_LOCATION }}-docker.pkg.dev

      - name: Build and Push Container
        id: build-push # Adding an ID to refer to outputs in later steps
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.WORKING_DIR }}
          file: ${{ env.WORKING_DIR }}/Dockerfile
          push: true
          tags: |
            ${{ env.AR_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.AR_URL }}/${{ env.IMAGE_NAME }}:latest

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.build-push.outputs.tags }} # Use the output from build-push
          format: sarif
          output: trivy-results.sarif
          exit-code: '1' # Fail this step on vulnerabilities found
          ignore-unfixed: true # Only show fixed vulnerabilities
          severity: 'CRITICAL,HIGH' # Customize to your desired level

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif