name: terraform-apply
on:
  pull_request:
    branches: 
      - main
    types: [closed]

jobs:
  terraform-apply:
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: 'true'
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}
          service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}

      - uses: hashicorp/setup-terraform@v2

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve

      - name: Generate Terraform docs
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          working-dir: ${{ env.WORKING_DIR }}
          output-file: README.md
          output-method: inject
          git-push: "true"